### PR TITLE
Feature/docker update

### PR DESCRIPTION
**Pull request by grasdk**
Resolves [issue 777](https://github.com/bpatrik/pigallery2/issues/777)

Also adds linting checks to dockerfiles and resolves linting errors. Linting errors about versioning packages are ignored (DL3008 and DL3018)

### CODE REVIEW

**Comment by bpatrik** [comment]
Thanks. I did not test how removing the `Volume` tags would change the behavior, but I will just take your word that it will just keep working.

**Comment by jdavidpeter** [comment]
To me it seems that the change of --update-cache  to --no-cache in the Alpine Docker file broke the build.
I can't build an Alpine Docker image on Raspberry Pi 5 using Ubuntu unless I revert that change.
@grasdk Would you kindly opine if this was an oversight?

**Comment by grasdk** [comment]
> To me it seems that the change of --update-cache to --no-cache in the Alpine Docker file broke the build. I can't build an Alpine Docker image on Raspberry Pi 5 using Ubuntu unless I revert that change. @grasdk Would you kindly opine if this was an oversight?

@jdavidpeter That seems weird, but if that is your experience, I can't contest it. `buildx` builds it for ARM64 which I believe is the rPi5 architecture. Can you install and run the edge image from docker hub?
docker pull bpatrik/pigallery2:edge-debian-bookworm

**Comment by bpatrik** [comment]
As far as I can tell buildx in github action works: https://hub.docker.com/r/bpatrik/pigallery2/tags/ last build was 2 months ago on all platforms

**Pull request merged**
