### PR TITLE
bug fixes of both issues of #838

### PR DESCRIPTION
**Pull request by kagahd**
- Bug 1 is fixed by converting a single String in `dc.subject` to an array of one String so that the loop iterates not over the characters of the String but over the String(s) of the array.
- Bug 2 is fixed by joining the full path to the filename without its file extension.

### CODE REVIEW

**Comment by bpatrik** [comment]
Thank you for your addition!

There as a bigger MetadataLoader.ts change with one the latest PR that conflicts with the PR. Can you please resolve the conflict?

**Comment by kagahd** [comment]
> There as a bigger MetadataLoader.ts change with one the latest PR that conflicts with the PR. Can you please resolve the conflict?

Hi @bpatrik, all merge conflicts due to PR #829 have been resolved.

**Comment by bpatrik** [comment]
Can you please rebase again?

There was a bug in the MetadataLoader over the week that got fixed now.

**Comment by kagahd** [comment]
Hi @bpatrik, all merge conflicts due to the bugfix of PR https://github.com/bpatrik/pigallery2/pull/829 have been resolved again for a second time.

**Comment by bpatrik** [comment]
Thanks!

The sidecar tests are failing, can you please take a look?

**Comment by kagahd** [comment]
> The sidecar tests are failing, can you please take a look?

Not for me 😄 
When I resolved the merge conflicts due to PR  #829, some sidecar tests also failed because of a different `creationDate`. However, my code does not touch `creationDate` at all. It seems that the `MetadataLoader.ts` changes done in #829 read the `creationDate` inconsistently. 
How to proceed? I can't reproduce the failing tests, see screenshot.
PiGallery2TestsOK

**Comment by bpatrik** [comment]
My guess those files do not have a creation date in metadata and app falls back to the filesystem's date, so the test are flaky. 

Did you happen to touch those files?

@grasdk do you have any idea?

I take a look later but I won't be at computer during the next few weeks.

**Comment by grasdk** [comment]
I'll take a look tonight CET.

@kagahd did you try removing the node modules dir or git clone your code into a new empty dir and rebuild everything from scratch? This would have an affect on the environment similar to what the automated test that fails has.

Also: what is your timezone? I added timezone support..if metadata does not have timezone, local timezone is assumed. Your timezone might not be the same as the build server's timezone, which may cause irreproducible test results between your environment and the build server's. You can mitigate that by.expmicitly adfing timezone offset tonyour test data.

/Regards

**Comment by grasdk** [comment]
@bpatrik was right. In the absense of reading creation date from metadata, file date was read. Since the test files were created at different times on the server and on @kagahd 's test environment, there was a failure.

I made a not-too-pretty pull request for @kagahd 's branch: https://github.com/kagahd/pigallery2/pull/1 that fixes the immediate problem. I think the test data that this PR brings is worth it.

Also I think that these tests will benefit the other pull request for metadata: https://github.com/bpatrik/pigallery2/pull/841

**Comment by kagahd** [comment]
Thanks @grasdk for the PR that I merged already. 
@bpatrik , this PR should now be ready to merge.

**Comment by bpatrik** [comment]
Thank you for both of you!

**Pull request merged**
