### PR TITLE
Attempt to fix not accessible password protected shares

### PR DESCRIPTION
**Pull request by jdavidpeter**
https://github.com/bpatrik/pigallery2/issues/630

### CODE REVIEW

**Comment by jdavidpeter** [comment]
This solution fails to provide the correct Unknown Sharing Key error page even if I try to access a non-existing share, so likely it's not good enough.

**Comment by bpatrik** [comment]
The sharing login is rather complex part of the app. I recommend doing a TDD approach and writing clear scenarios as test cases. They should go somewhere here: https://github.com/bpatrik/pigallery2/blob/master/test/backend/integration/routers/SharingRouter.ts

**Comment by bpatrik** [comment]
this should be fixed by now.

**Comment by jdavidpeter** [comment]
Thank you!

**Pull request closed without merging**
