### PR TITLE
removed ts-node-iptc dependency. 

### PR DESCRIPTION
**Pull request by grasdk**
The only metadata parser for photos and sidecars in MetadataLoader is exifr after this PR

Some natural simplification came to the logic of Metadataloader as a consequence.

### CODE REVIEW

**Comment by bpatrik** [comment]
Whoho great!

Thanks#

**Comment by bpatrik** [comment]
For some reason the review button does. It work...

Can you remove the SQL db file pls?

**Comment by grasdk** [comment]
> For some reason the review button does. It work...
> 
> Can you remove the SQL db file pls?

Hehe, yes. I found out that I already removed it. It was there before. My PR removed it. :)

**Comment by bpatrik** [comment]
Haha, thanks!

**Pull request merged**
