### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by vdergachev**
Please do not merge it right now, i wanna test it carefully

### CODE REVIEW

**Comment by bpatrik** [comment]
Hi,
Let me know when I can merge it. 
Also, there was a bug with the translations (If you were wondering why some of the translations are not working) that I fixed with the latest commit.

**Comment by vdergachev** [comment]
Hi,
i'm going to update translation during the day, i found following values on settings page which stays in English after switching to another languages:

- Simplified/Advanced switch
- Enabled/Disabled (all switches)
- Ascending/descending by name and date values
- Low/medium/high in sensitivity drop down

**Comment by vdergachev** [comment]
Do i need to regenerate xlf file for Russian language?

**Comment by bpatrik** [comment]
Those errors should be fixed with the latest commit.  You don't need to recreate the translation.

I've recently added few more texts to the translation.
you may call `npm run update-translation` to add those to your translation.
The command adds new text to the  `messages.{locale}.xlf` files, without touching the already present ones.

**Comment by vdergachev** [comment]
I updated translation, i hope now it's more understandable and convenient for Russian non IT people.
All problems mentioned above is gone.

**Comment by bpatrik** [comment]
Thank you very much.
As the page evolves, It might happen in the future, that I add/remove/change some of the texts.
In that case the Russian version will contain the original english text until someone fixes it.

**Pull request merged**
