### PR TITLE
Support exiftool face region format

### LINKED ISSUE #191: Face regions not detected
**Describe the bug**
I am trying to load my own photos into Pigallery2 and get it to recognize my face regions.

I have now downloaded the example photo and modified it by setting a region value (same value):
```
exiftool '-RegionAreaH=0.55270' IMG_6253.jpg
```
But as soon as I modify any tag, it seems that Pigallery2 does not recognize the face region anymore. I tried diffing the exiftool output:
```
$ diff non-working.txt working.txt
144,147c144,147
< [System]        FileAccessDate                  : 2020:10:18 17:10:45+02:00
< [System]        FileInodeChangeDate             : 2020:10:18 17:14:04+02:00
< [System]        FileModifyDate                  : 2020:10:18 17:10:23+02:00
< [System]        FileName                        : IMG_6253_not-working.jpg
---
> [System]        FileAccessDate                  : 2020:10:18 17:09:17+02:00
> [System]        FileInodeChangeDate             : 2020:10:18 17:08:09+02:00
> [System]        FileModifyDate                  : 2020:10:18 17:08:09+02:00
> [System]        FileName                        : IMG_6253_working.jpg
149c149
< [System]        FileSize                        : 889 kB
---
> [System]        FileSize                        : 884 kB
```

**Photo/video (optional) that causes the bug**
Not working:
IMG_6253_not-working
Example image (working):
IMG_6253_working

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Used app version**:
- docker-nightly (git hash: acd3cf1fe52038790269cda30454fb21f12d4db4)

### PR DESCRIPTION
**Pull request by lbischof**
This change adds support for face regions that were added with Exiftool. I'm not sure about the `as any` part. I haven't worked with Typescript before. 

I think this could probably be improved with `for (const region of regions)` or similiar, but I did not want to bloat this pull request.

Fixes #191

### CODE REVIEW

**Comment by bpatrik** [comment]
I think its okay. I might rearrange it, bit it does the job.
Would you mind moving the image from the demo folder to the tests/assets and write a test to it?
The test should go here: 
https://github.com/bpatrik/pigallery2/blob/master/test/backend/unit/model/threading/MetaDataLoader.spec.ts
So that we wont brake this in the future.

**Comment by lbischof** [comment]
Sure, I will try writing a test.

On Saturday, October 31, 2020, Patrik J. Braun <notifications@github.com>
wrote:
> I think its okay. I might rearrange it, bit it does the job.
> Would you mind moving the image from the demo folder to the tests/assets
and write a test to it?
> The test should go here:
>
https://github.com/bpatrik/pigallery2/blob/master/test/backend/unit/model/threading/MetaDataLoader.spec.ts
> So that we wont brake this in the future.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/zBeAmqxd4z82mbp_Z5V7-NnTd34t1kaLqTjml7mcRFxMLj4hqsCkwIDd0Btl70k35BvWcoqEXtMrou9Z5Vv4ZMwG19OaDiwTgoEYVDbYGK0qbxt3ee6e3XgdtHWBM9ydk4sJ459QSiGzZsBDAFRv51wb26HEy9fVG4w1BEBOCXS5kwRzxXjhfdDqsa5ncUup0ntlEXHPG5N8qIZBLwVqei8HS1t-WKbvm3d07moX1A=s0-d-e1-ft#https://github.com/notifications/beacon/AAOAVHMCTKSHFI3EZCJ74UTSNRSWZA5CNFSM4TCJQO2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFLVAHCY.gif>

**Comment by bpatrik** [comment]
Thanks for the contribution, I merged it and added the tests

**Comment by lbischof** [comment]
Thanks and sorry I did not get around to doing it myself

**Pull request merged**
