### PR TITLE
Polish translation added

### PR DESCRIPTION
**Pull request by gklebus**
Please review & add to the project - provided Polish translation for pigallery2.

### CODE REVIEW

**Comment by bpatrik** [comment]
Thank you!

**Comment by jezikk82** [comment]
Had it been included into any of the docker nighty releases ?

**Comment by bpatrik** [comment]
I see it in the demo app:

kép

**Comment by akwodkiewicz** [comment]
[Looks like](https://hub.docker.com/r/bpatrik/pigallery2/tags/?page=1&ordering=last_updated&name=latest) the tags:

- `latest-alpine`
- `latest-debian-buster`
- `latest-debian-stretch`

were last pushed 8 days ago, but the tags:

- `latest`
- `latest-stretch`

were last pushed 2 months ago.

**Pull request merged**
